spring.application.name=social

#spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
#spring.datasource.username=postgres.hvaujecnmqehiofmwkkg
#spring.datasource.password=6icFAqfrz5LKluwc

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=cavallini
spring.datasource.password=admin

spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=none

spring.flyway.baseline-on-migrate=true

api.security.token.secret=${JWT_SECRET:minha-secret-key}

#spring.security.oauth2.client.registration.github.client-id=Ov23ct0EPIaItqofgH6H
#spring.security.oauth2.client.registration.github.client-secret=acbe1656695cf4b2d0dda253f780033b94259ef8