spring.application.name=social

spring.datasource.url=jdbc:postgresql://localhost:5432/social
spring.datasource.username=cavallini
spring.datasource.password=admin

api.security.token.secret=${JWT_SECRET:minha-secret-key}

#spring.jpa.hibernate.ddl-auto=update